# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-02-18 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms_app', '0002_auto_20180217_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='hasan', max_length=20),
            preserve_default=False,
        ),
    ]
